### ISSUE TITLE
Errror when run demo ?

### ISSUE THREAD

**Issue by ThorPham** [mjq11302010044/TPGSR#9]
I use GPU when inference but i don't know why error  . Which one model run on CPU ?

> loading pretrained crnn model from crnn.pth
  0%|                                                                                                                                                   | 0/4 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/thorpham/Documents/challenge/super-resolution/TPGSR/main.py", line 76, in <module>
    main(config, args, opt_TPG=opt)
  File "/home/thorpham/Documents/challenge/super-resolution/TPGSR/main.py", line 16, in main
    Mission.demo()
  File "/home/thorpham/Documents/challenge/super-resolution/TPGSR/interfaces/super_resolution.py", line 1480, in demo
    images_sr = model(images_lr)
  File "/home/thorpham/anaconda3/envs/torch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/thorpham/Documents/challenge/super-resolution/TPGSR/model/tsrn.py", line 195, in forward
    spatial_t_emb = self.infoGen(text_emb)
  File "/home/thorpham/anaconda3/envs/torch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/thorpham/Documents/challenge/super-resolution/TPGSR/model/tsrn.py", line 103, in forward
    x = F.relu(self.bn1(self.tconv1(t_embedding)))
  File "/home/thorpham/anaconda3/envs/torch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/thorpham/anaconda3/envs/torch/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 916, in forward
    return F.conv_transpose2d(
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking arugment for argument weight in method wrapper_slow_conv_transpose2d)

**Comment by mjq11302010044** [comment]
@ThorPham Hi, have you altered the code by yourself or you run the test with multi-gpu? Our model may have some bugs when runing the test with multi-gpu process.

**Comment by mjq11302010044** [comment]
@ThorPham Also you may try to figure out which device the input arguments are in. This may help you figure out the buggy part.

**Comment by ThorPham** [comment]
Thank you
